### ISSUE TITLE
Perform a release using Github Actions pipeline

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#1022]
- [ ] Disable Travis pipeline
- [ ] Ensure GitHub actions deploy to Openshift (dev)
- [ ] Ensure GitHub actions deploy to Openshift (staging)
- [ ] Ensure GitHub actions generate signed JARs
- [ ] Perform a release

**Comment by nitch2019** [comment]
Need release to publish FireFly App Exporter to dockerhub
