### ISSUE TITLE
Next Milestones

### ISSUE THREAD

**Issue by nitch2019** [adorsys/open-banking-gateway#1081]
We need to discuss what should come as next
- Autorisation Protocol ( we already implemented Redirect, Embedded and Decoupled) - what next?
- Multibasketing?
- Which payment as next?
- Styling of the UI? (Fintech UI or Consent UI?) - as TPP UI and Online Banking are under Dynamic Sandbox Project
- Consistent Naming (API Refactoring?)
- Video Tutorial (Priority regarding other tasks?)

**Comment by nitch2019** [comment]
Styling UI: Could it look nicer (refer to FireFly, ....) -> Designer
Consistent Naming: Website issue (Modelbank, xs2a Sandbox, OBG) -> have to be sync with Marketing and evtl need to be fixed by dev
Video Tutorial (with Maisoora)
Autorisation Protocol : After Dev, we will go the sample application
Refactoring API: we need to have a stable API before having more Applications using the OBG
Which payment as next?: Polish what we have and let the market decide. 
Multibasketing: Less important as the marketing tasks

**Comment by gatiskalnins** [comment]
1. Styling UI: currently doesn't appear to be a need for it. If a need for redesign arises, issue will be revisited.
2. Consistent naming: change the scope of the activity to:
 2.1. Limit scope to only OBG
 2.2. Have a complete review of documentation on GitHub. Goal: ensure that it reflects the current state of the product. Remove outdated and incorrect information, for example, not yet existing adapter facades from diagrams (Polish API, Open Banking UK etc.), outdated release details etc.
   -> separate issue
3. Video tutorial: currently stay with video from Peter. In case a new one is required, a new issue will be created.
4. Authorisation protocol: unclear what is meant. @nitch2019 do you recall?
5. Refactoring API: to be checked with developers.
6. -
7. Multibasketing: @nitch2019 what is meant by this?

**Comment by VanessaAhmad** [comment]
Currently working out the next milestones/ direction of the OBG
