### ISSUE TITLE
BUG loa for xs2a via fintech not more possible when error occured once

### ISSUE THREAD

**Issue by electronicpeter** [adorsys/open-banking-gateway#1138]
When Consent in OBG is no more valid, the consent must not be send by FintechServer. This feature was already implemented and working. Now it is no more working. To reproduce error Create Consent for xs2a bank one time, ask 24 times for list of accounts and than consent is no more valid. Than go to settings of fintech UI and switch on Option

Discard propably existing consent ONE TIME ONLY.

Now consent should not be send from FintechServer to OBG. But it is.

For whatever reason, this error remains, even if user logs out and logs in with another user id. So error is highly propable in errorhandling component of fintech ui.

**Comment by electronicpeter** [comment]
Error might be in UI not telling Server any more to ignore Consent.

**Comment by rjtch** [comment]
Peter Errorhandler doesn't do anything else than catching client error and showing it to the user on fintechui! I've tried to reproduce the error and don't see anything anormal on fintechui. So after using consent 24 times i get the error that the consent is no more valid and when i switch in the settings and choose to discard the existing consent ONE TIME ONLY i get the same error that the consent is no more valid.
