### ISSUE TITLE
As a PSU, I want to select my bank, so that i can see the bankprofile showing the open banking service offered by my bank

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/open-banking-gateway#13]
Acceptance criteria: 

- PSU selects one of the list entries 
- The Bankprofile must be the result of this use case 
- The Bankprofile have the list of Banking services provided by the BankingApi of the bank (("get transactions" in this case)
   

[Use cases description](https://github.com/adorsys/open-banking-gateway/blob/gh-pages/docs/architecture/3-selectBank.md)

**Comment by VanessaAhmad** [comment]
one negative test is missing (Bank that doesnt offer all services)
