### ISSUE TITLE
Setting Up the Banking Gateway Project Environment 

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/open-banking-gateway#2]
- [x] Create GitLab project for storing the deployment configuration.

- [x] OpenShift project open-banking-gateway-dev. 

- [ ] Adapt helm configs of the existing banking-gateway: sandbox (release), adapter (first release, later perhaps develop), b2c?. (Estimation: 2d)

- [ ] Create new helm config for open-banking-gateway application. (Estimation: 1h)

- [ ] Create new helm config for open-banking-gateway postgres database. (Estimation: 1h)

**Comment by tnein** [comment]
https://git.adorsys.de/adorsys/open-banking-gateway-deploy

**Comment by tnein** [comment]
https://openshift.adorsys.de/console/project/open-banking-gateway-dev

**Comment by tnein** [comment]
Moved to more detailed tasks:
#106
#48
