### ISSUE TITLE
check database encoding

### ISSUE THREAD

**Issue by vladimir-nechai** [adorsys/open-banking-gateway#238]
In Database some special characters are displayed with `?`

**Comment by max402** [comment]
Umlaut problem comes from csv file. Mark promised correct at least Sparkasse and Fiduchia banks this week. Then we can update our source file

**Comment by tnein** [comment]
Used database encoding in our deployments (OpenShift):

```
sh-4.2$ psql
psql (10.6)
Type "help" for help.
postgres=# \c open_banking
You are now connected to database "open_banking" as user "postgres".
open_banking=# SHOW SERVER_ENCODING;
 server_encoding 
-----------------
 UTF8
(1 row)
```

:heavy_check_mark: UTF8
