### ISSUE TITLE
Map xs2a protocol response to OPBA rest API

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#260]
We need to map customary response from Xs2a protocol to OPBA REST API entities

- [ ] mapper accounts xs2a 2 facade including test
- [ ] mapper accounts facade 2 rest including test
- [ ] mapper transactions xs2a 2 facade including test
- [ ] mapper transactions facade 2 rest including test
- [x] adapt technical ui to show results of list accounts
- [x] adapt technical ui to show results of list transactions
- [x] change mapper to inner classes of controller and add spring keyword as requested by valentyn

**Comment by valb3r** [comment]
See https://github.com/adorsys/open-banking-gateway/pull/258 for details

**Comment by electronicpeter** [comment]
Module: xs2a-protocol
AccountListingService does the specific call, if the XS2A-Adapter is to be used for the customers bank. For that this service gets xs2a-Adapter specific result, the AccountListHolder. This class is stored in the flowable context as the RESULT object.

The ContextUtil (also part of the xs2a-protocol module) has the task to map the
AccountListHolder (xs2a-specific) to the AccountListBody (not xs2a-specific).

The AccountListBody is in the opba-facade-protocol-api-shard module. This module does not
know anything about xs2a and obviously has no dependencies to xs2a. 

So my first task is to map all the fields from the

(XS2a) AccountListHolder to the
(facade) AccountListBody.

For that I have to give the (facade) AccountListBody a bunch of fields. In the first draft these fields
will be all the fields of the AccountListHolder.

Eventually the TppFacade has to return the AccountList defined in 
/opba-banking-rest-api/src/main/resources/static/tpp_banking_api_ais.yml

So why would we have a second mapping from the facade AccountListBody to the (opan-api)AccountList.
Why does (facade)AccountListBody not directly contain the (open-api)AccountList ?

**Comment by valb3r** [comment]
See:
https://github.com/adorsys/open-banking-gateway/pull/225#discussion_r374533726

It is mostly to decouple REST API from a protocol implementation, you can do it as pass-through, but we should allow protocol-api to evolve separately to rest-api. If we would use the same objects then we can't remove or add technical fields easily as they are part of public REST API. 
For example, a protocol may expose some technical fields which we should filter

**Comment by electronicpeter** [comment]
So, eventually two Mappers have been created:
1) XS2aToFacadeMapper in module  xs2a-protocol. Mapper is called in Xs2aResultBodyExtractor.
2) FacadeToProtocolMapper in module opba-facade-protocoal-api-shared. Mapper is called in AccountListBody.
