### ISSUE TITLE
Add sessionPassword to API, technical-UI and notify FinTech examples about it

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#288]
FacadeServiceableRequest {
private final String sessionPassword;
}

Is not set anywhere

Francis wants to review the concept and adapt the approach of xs2a core where we circulate ID and secret key together -> create session; dont forget FinTech Server

**Comment by VanessaAhmad** [comment]
Francis wants to have a discussion with Peter and Max about it
