### ISSUE TITLE
Add currency support to account reference (open api)

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#299]
Currently, our API is defined as List<string> accounts meaning only IBAN list for accounts. It is incorrect - we should support at least account currency to specify account. 
So account is something like:
AccountReference {
iban
maskedPan (optional)
currency (optional)
}

Also we need to fix technical UI and corresponding mappers

**Comment by VanessaAhmad** [comment]
low priority not part of MVP

**Comment by nitch2019** [comment]
Currency should be created in the FintechUI.
