### ISSUE TITLE
List transactions hack fix

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#316]
Currently, due to bug 
https://github.com/adorsys/xs2a-connector-examples/issues/3
`List Transactions` is not working. As a hack, ledgers version was downgraded and stub field was added. 
We need to upgrade Sandbox and ledgers as soon as https://github.com/adorsys/xs2a-connector-examples/issues/3 is resolved. Also, we need to remove hardcoded EUR currency

**Comment by VanessaAhmad** [comment]
low priority, not part of MVP
