### ISSUE TITLE
Redirection with 303 when consent is present, but not all parameters were passed should be disallowed

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#318]
Currently, when you call GET /transactions given consent to get transactions is present, but the call is missing `dateTo` or `dateFrom` Xs2a protocol will notify that redirection is needed because not all parameters were present.
This valid behavior of the protocol. The problem is facade does not check that it is `redirect` with existing consent and instead of throwing ErrorResponse, issues RedirectResponse

**Comment by VanessaAhmad** [comment]
need to be checked (low priority, not part of security)
