### ISSUE TITLE
Codecov badge is wrong

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#320]
Currently codecov badge reports coverage of last pull-request, we need to fix this, so that it reports only develop branch.
See the [Datasafe](https://github.com/adorsys/datasafe/) for an example of how to fix it:
https://github.com/adorsys/datasafe/blob/develop/.travis/codecov_bash.sh

**Comment by VanessaAhmad** [comment]
needs to be checked, maybe already fixed, low priority
