### ISSUE TITLE
Use triggerAsync for all Flowable triggers

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#322]
We should use triggerAsync instead of trigger for the cases like 
`runtimeService.trigger(execution.getId());`
Synchronous triggering within inner execution causes OptimisticExceptions because we are doing concurrent change within same transactions

**Comment by valb3r** [comment]
TODO: Check it

**Comment by VanessaAhmad** [comment]
low priority, not part of MVP
