### ISSUE TITLE
resolve redirect problem

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#325]
- [x]  adapt fintech server to use new tpp api
- [x]  set matching fintech id and password
- [ ] change api between fintechserver and fintech ui for redirect

**Comment by electronicpeter** [comment]
- [x ]  adapt fintech server to use new tpp api
- [x]  set matching fintech id and password
- [ ] change api between fintechserver and fintech ui for redirect

**Comment by electronicpeter** [comment]
Currently problem is

Fintech-Server sets fields:

- Access-Control-Allow-Origin
- Access-Control-Allow-Credentials
- Access-Control-Allow-Methods

But browser is not redirecting. Message is:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:5500/parameters/provide-more/18a27e1e-5c9b-….accountaccess%7D%22,%20%22target%22:%22AIS_CONSENT%22%7D%5D. (Grund: Berechtigung/Credential wird nicht unterstützt, wenn die CORS-Kopfzeile 'Access-Control-Allow-Origin' auf '*' gesetzt ist).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:5500/parameters/provide-more/18a27e1e-5c9b-….accountaccess%7D%22,%20%22target%22:%22AIS_CONSENT%22%7D%5D. (Grund: CORS-Anschlag schlug fehl).

**Comment by electronicpeter** [comment]
Even setting ccess-Control-Allow-Origin to the origin (e.g. localhost:4444 or 4200) does result in same message.
