### ISSUE TITLE
configuration of database for the FinTech Server

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#332]
adjust configuration of database for the FinTech Server

**Comment by tnein** [comment]
fintech server needs database

proposal to use existing one (obg-db)
therefore rename it
and either add separate database or schema for fintech server

**Comment by tnein** [comment]
(/) migrate postgres to serve multiple databases
(/) add db to fintech server
=> postgres driver missing, waiting for application team

**Comment by tnein** [comment]
Hi @electronicpeter,
could you please create the driver task as dependency of this one?
Best regards,
Tarkan
