### ISSUE TITLE
update links to sandbox

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#339]
update the links to the sandbox ("Test Bank") in our bank database

https://obg-testbank-developerportalui.cloud.adorsys.de/

**Comment by tnein** [comment]
open banking gateway application already is connected to the new sandbox:
`SPRING_LIQUIBASE_PARAMETERS_ADORSYS-SANDBOX-URL: "https://obg-testbank-developerportalui.cloud.adorsys.de/"`
