### ISSUE TITLE
Consent Authorisation UI Result Page

### ISSUE THREAD

**Issue by vladimir-nechai** [adorsys/open-banking-gateway#355]
Result Page showing the result of the consent authorisation. As an example Redirect page from Fintech UI.

- Redirect card centered on the screen
- In Consent UI it is `ResultPageComponent` with the route locally [http://localhost:4200/ais/consent-result](http://localhost:4200/ais/consent-result)

**Comment by electronicpeter** [comment]
Hi switched to branch
feature/OBG-355-to-fintech-screen

I did mvn clean install -DskipTests
I started postgres with port 5432
And then

mvn -Dspring.profiles.active=dev,no-encryption,technical-ui spring-boot:run -f opba-embedded-starter/pom.xml

lead to Caused java.nio.file.FileSystemNotFoundException.

See logfile attached here[https://app.zenhub.com/files/219286039/dc9b8a8b-5654-4356-990d-8c664b3c2334/download](https://app.zenhub.com/files/219286039/dc9b8a8b-5654-4356-990d-8c664b3c2334/download)

**Comment by valb3r** [comment]
@electronicpeter 
1. If you want to pass profiles to spring-boot using maven - use
`-Dspring-boot.run.profiles=dev,no-encryption,technical-ui`
2. Currently, some resources are not placed directly with opba-starter, so if you want to run from maven use:
`mvn -Dspring-boot.run.profiles=dev,no-encryption,technical-ui spring-boot:run -f opba-embedded-starter/pom.xml -Dspring-boot.run.jvmArguments="-Dpkcs12.keyStore=../opba-protocols/xs2a-protocol/src/main/resources/sample-qwac.keystore"`
