### ISSUE TITLE
As a PSU, I want to search the bank by auto-completion by entering keywords so I can find my bank

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/open-banking-gateway#4]
Purpose: We need a uniform API to enable communication with FinTech Data Center.

Acceptance criteria:

- The search is done by automatic completion
- The keyword to be entered must consist of at least 3 characters
- A bank list is the result of this use case 
- The list is displayed as return in the server

The Banking Gateway offers a bank search interface for this purpose

[Use case description](https://github.com/adorsys/open-banking-gateway/blob/gh-pages/docs/architecture/2-searchBank.md)

**Comment by valb3r** [comment]
@francis-pouatcha 
[MVP2]
https://github.com/adorsys/open-banking-gateway/blob/gh-pages/docs/architecture/2-searchBank.md#use-case-steps-1
`Local Incremental Search`
This does not really require Lucene - all we need is embedding lunr.js into frontend and serving pre-built index directly to client. There are totally ~32k banks and probably we will serve much less - so data payload is somewhere near 10-20Kb of full bank search cache. At least it is worth considering

**Comment by valb3r** [comment]
@max402 Please use OpenAPI for documentation (not swagger), see keystore-keymanagement for details

**Comment by max402** [comment]
- [ ] fill database with test data (BE);
