### ISSUE TITLE
Design Concept on how to implement PsuAuthData and DataEncryption in Tpp Server

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/open-banking-gateway#482]
Here  the draw.io
<mxfile host="Electron" modified="2020-03-27T15:00:01.467Z" agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/12.3.2 Chrome/78.0.3904.113 Electron/7.1.2 Safari/537.36" etag="P89UYD1DvmoboiJ8Tgpq" version="12.3.2" type="device" pages="1"><diagram id="mnaltLRyI_7yfEfA4HFp" name="Page-1">5VlNc5swEP01nkkP7oAI2D7aTtJOm04z40ObowIyqBEsFSI2/fWVjDAfwo3b2LHb5hCklRZJb/c9Fjxw5vH6Hcdp9AkCwgbICtYD52qAkG1bnrwoS1FaRmO7NIScBnpSbVjQH0QbLW3NaUCy1kQBwARN20YfkoT4omXDnMOqPW0JrL1qikNiGBY+Zqb1Cw1EVJ3Lm9QD7wkNI730GI3KgRhXk/VJsggHsGqYnOuBM+cAomzF6zlhCrwKl9LvZsfodmOcJGIfh0m8uC4KsD57/nBpf/CcVfFhqDf7hFmuD6w3K4oKAQ55EhB1E2vgzFYRFWSRYl+NrmTMpS0SMZM9Wzb17QgXZL1zn/b29DJtCMRE8EJO0Q6OowHTGXNpO2V/VePvVekRNaC3J/o0WMc83N67hkU2NDK/gZLtPoMKcBFBCAlmtwCpxuIbEaLQGY1zAW2kyJqKr8r9rat7942Rq7W+86ZT6E65CxIYKdvBVu4Ucu6TXx1JcwnzkIhfzUP9weKEYUGf2hs5PPA96ekxud9ZluKkFRHve66YVCboMCszdCqnJMBjzOoJshWqa5rl01xEV1jgiyXHiU+zwaW1pIkgfqRWLheS+y7XKr0q8wN/2eoHPceQJP7wkRRD+83ObZ+Y1TZqsxpVLG+wGnk9rK5sB88t5BmgKGYtdDeBRF5mJ+G5xJQXDSfVvW+O1W6bXuWXSTqLqXrqSYPPcJZRvzLfUNYO50FkBO0pI8g9pYygk8kI+itlBJ2tjFyO95CRvuLgaDLinF8FNTo7rfUMkFS6SZeaKY4BmwRAtLHJBIdHMgcGvFbopRS2jgkzGiZKAiVgRNpnCk4qi/qpHohpEKhleoPRDtcrxWP7fGzGAx0rHrapiErAFgI4uQHeVw9JSZg3VasUhAuRpnKW+q+GrUpB6htshrpub07OEcftvGX0ccTqiYl7tJiYSnKxZUkTYF6kgkLykRQmjP8OZ0bt+LiOa3Jm1BOf0dHqRVPYj1kvVu09qkXZuSOcymOqwHUqyFb9WJeTOyrIA5aG9njf2nBHJrzSK+bYoN2NFq9uuLMIp6qZx2zqC2iS5BY/EHYHGVXMlFMeQAiI5QSmBmbYfww3mVGRboCc5eavh2gCOnIHuWA0kRyuPnEdiGOdDy3uyJRA51XfyCwD8r+BYb/3jnZIhk1eSBztegfyIV+nBXLd/nKlukXJaO3Vifl2Gy9g5OS/ZeS24qi+lp+akeYHOFl2bMvEfYq/Myj1vI7OXZ76dQi5BqzPlN/o9DC64+crZnsyMWH8g4pZdusfRkpdqX9ecq5/Ag==</diagram></mxfile>

**Comment by max402** [comment]
![security_opba](https://user-images.githubusercontent.com/1208396/78043666-ea721600-7373-11ea-8261-af0d5a391d32.png)
