### ISSUE TITLE
Dialogs should be higher

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#508]
![image.png](https://images.zenhubusercontent.com/5de7892cfa46ac657aec2a82/4c934c45-ae84-436d-82c2-75c3fbf94a51)

This is where the dialogs are displayed now, but they should rather be displayed like this:
![image.png](https://images.zenhubusercontent.com/5de7892cfa46ac657aec2a82/860359d3-391f-45d6-be7b-7ce6c83c3d72)

**Comment by alexosm** [comment]
check it out
