### ISSUE TITLE
Design concept for faster travis build

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/open-banking-gateway#52]
Travis build already taking 10 minutes and project hasn't started yet. Can we optimize it?
See: https://travis-ci.com/adorsys/open-banking-gateway/builds

**Comment by valb3r** [comment]
Travis CI seem to throttle builds or run them on very limited hardware - Postgres in test containers inside travis has appalling performance - 8 requests/s for trigram search, while locally it easily handles 100 requests/s and more with more threads. This applies both to Postgres-tmpfs and non-tmpfs versions. Same observed for liquibase migrations performance

**Comment by tnein** [comment]
deprecated due to #338:
migrating to github actions will help with performance
