### ISSUE TITLE
Encode BankingProtocol selection information into the redirectCode

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/open-banking-gateway#54]
The redirectCode is generally used to:

- Securely redirect the PSU UserAgent from the TppBankingApi (InitConsent-067) over the FinTechApi (InitConsent-069) to the ConsentAuthorizationApi (Redirect-010).
- Securely redirect the PSU UserAgent back from the ConsentAuthorizationApi to the TppBankingApi over the FinTechApi. See AuthEmbedded-094, AuthRedirect-081, Service-010, Service-030

This redirectCode is the only information available to the target of the redirection and thus, must contain information necessary to retrieve the banking protocol instance to use.

As the redirectCode is opaque to the BankingProtocol module, it might make sense to implement this as part of the BankingProtocolSelector. Like: BankingProtocolSelector.select(redirectCode):BankingProtocol thus hiding the encoding in the BankingProtocol subsystem.

**Comment by francis-pouatcha** [comment]
Hello Denys, this is another situation where we need the information associated with the BankingProtocol.

**Comment by francis-pouatcha** [comment]
BankingProtocolFacade defines general objects for the domain specific mapping of information we need to process the service calls those are saved in an enum map.

**Comment by VanessaAhmad** [comment]
ToDo
change the documentation to reflect the implementation
