### ISSUE TITLE
Bank profile online configuration

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#602]
We need to have the bank profile configuration UI and backend to cover these cases:

- [ ] Select redirect or embedded approach preference for a bank
- [ ] Preferred payment format for a bank (XML or JSON)
- [ ] Consent conflict resolution strategy configuration - when FinTech acquires Consent that is extremely broad, how to deal with already existing one (see https://github.com/adorsys/open-banking-gateway/issues/519 )
- [ ] Dynamic rules configuration for what parameters to ask from PSU. For example, PSU_ID maybe mandatory today for some bank, but tomorrow it is optional or even causes error thrown by ASPSP-API (and we have shipped the software to client and he does not want to upgrade it)
- [ ] ASPSP-API endpoint configuration - i.e., URL and some special parameters for Xs2a-adapter (i.e. OAuth URL)
- [ ] Default values for typical consent parameters - i.e., consent usage frequency per day if not specified by FinTech

To cover these cases we need either UI and API that allows OPBA server configuration, or we need to use Spring-Cloud-Config for dynamic configuration of Spring application

**Comment by valb3r** [comment]
This is primary approval question

**Comment by DG0lden** [comment]
To me this sounds like help-tool to configure the bank in our Bank Database (Bank-search component)... Sure, needs to be discussed.
