### ISSUE TITLE
Wrong IBAN flag not working

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#616]
When entering the wrong IBAN to Consent Authorization user is redirected back to the IBAN input page. Redirected URL has wrong=true query param that indicates the necessity of showing an error message to the user. The error message is not shown.

Example URL:
https://obg-dev-consentui.cloud.adorsys.de/ais/2705f673-b1f2-4a13-8796-9f4db9e8426a/entry-consent-transactions/dedicated-account-access?wrong=true
`wrong=true`

**Comment by collins-k** [comment]
@valb3r yes because the user first has to click outside the input field. The only validation we have is on the length of the IBAN, right?

**Comment by valb3r** [comment]
@collins-k 
To see that previous IBAN is wrong, user should not click somewhere, it must be present when page loads

The only validation we have is on the length of the IBAN - yes, but probably we can do better validation

**Comment by collins-k** [comment]
@valb3r Ok I see the `wronngIban` attribute is never use
