### ISSUE TITLE
Smoke tests need to be fixed

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#627]
Currently, smoke tests (OpbaApiSmokeE2ETest, OpbaApiWithConsentUiSmokeE2ETest) are failing because `withSignatureHeaders` are statically hardcoded. It is better to use dynamically computed signature headers as they are necessary to fix this issue

**Comment by ivaniuminov** [comment]
This task was implemented within https://github.com/adorsys/open-banking-gateway/pull/692
and https://github.com/adorsys/open-banking-gateway/pull/639 pull request, which are already merged
