### ISSUE TITLE
Cookie renewal

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#632]
We need to be able to renew Authorization-Session-Key cookie if it is about to expire.
1. We need an endpoint to exchange old cookie to new cookie
2. We need a frontend to watch for cookie age and update it if the cookie will expire soon usnig endpoint from p.1

**Comment by DG0lden** [comment]
The comments from PR https://github.com/adorsys/open-banking-gateway/pull/669 were not fixed. Therefore, task cannot be considered as Done.
Feedback from FE Team is also required.
