### ISSUE TITLE
When clicking on login button on registration screen redirectCode is lost

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#656]
When coming from FinTech for Accounts consent and landing on Login screen - click on register for new user and then on Register form click Login button and try to login with the existing user - it will fail as redirectCode will be lost.

**Comment by collins-k** [comment]
`redirectCode` can be retrieved from sessionStorage because it was saved there the first time the login page loaded. Just get it from there if there is no code in the route.
