### ISSUE TITLE
Adjust Input pin screen for other types of challenges

### ISSUE THREAD

**Issue by vladimir-nechai** [adorsys/open-banking-gateway#662]
Adjust Input pin screen in Consent UI for other types of challenges, such as photo Tan or QR code
(In embeddded mode, we need space to see the photo tan)

**Comment by VanessaAhmad** [comment]
BE does not support photo Tan and QR Code yet

**Comment by DG0lden** [comment]
@VanessaAhmad 

Decoupled shall be fully functional at Sandbox given you find the way to communicate TAN to ledgers (even static one). There is an issue for this already: https://git.adorsys.de/adorsys/xs2a/psd2-dynamic-sandbox/-/issues/510

For QR-Codes, PhotoTAN - it's just a matter of transferring some picture in embedded mode from Bank to User through TPP and putting TAN Back. It's not done for now, please raise an issue at Sandbox, shall not be very complicated
