### ISSUE TITLE
FinTech UI initiate Payment

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#699]
* [ ] ui pages
* [ ] fintech server api
* [ ] fintech server impl connecting to tpp

![image.png](https://images.zenhubusercontent.com/5de7892cfa46ac657aec2a82/2298b11a-d862-41a3-aff3-8d91eb7b3cd3)

For initiating payments and filling in required information you can use this style.
The fields should be:
- Name
- Iban debitor 
- Iban creditor
- amount
- purpose of payment (Verwendungszweck)

then confirmation page, which gives PSU opportunity to continue or return to previous page:
![image.png](https://images.zenhubusercontent.com/5de7892cfa46ac657aec2a82/ef123d40-20b6-4fe1-a849-ea24a3debd39)

As user will be redirected to Consent-UI this page should contain logo of redirection.
this page should have same information but as read only:
- Name
- Iban debitor 
- Iban creditor
- amount
- purpose of payment (Verwendungszweck)
- button ok (goes to consent UI page)
- button cancel (goes back to Payment initiation -> previous page)

Call needs to be done from FinTech UI to FinTech and from FinTech to TPP
additionally to required fields for payments, the redirect links have to be passed until TTP (as done in List of Accounts)

**Comment by electronicpeter** [comment]
Hi Collins, I continued on your branch with new branch with OBG-699-fintech-impl. So when you merge your branch to develop you can delete branch but please dont close issue as I am doing the BE stuff here.

**Comment by collins-k** [comment]
Why are u working from my branch? You are supposed to work on the BE and both are independent. If you want to work on it I will take another ticket and you finish this one.
