### ISSUE TITLE
Creating documentation framework/process

### ISSUE THREAD

**Issue by max402** [adorsys/open-banking-gateway#7]
creating basic mavin configuration of project, travis pipeline

**Comment by DG0lden** [comment]
Proposal of mkdocs can be seen here: https://github.com/DG0lden/mkdocs-demo/
Corresponding Github Pages: https://dg0lden.github.io/mkdocs-demo/
Optional usage of Readthedocs.org: https://dg0lden-mkdocs-demo.readthedocs.io/
