### ISSUE TITLE
Update openshift OBG Bank Dev to new Sandbox

### ISSUE THREAD

**Issue by max402** [adorsys/open-banking-gateway#714]
Payments in redirect mode work only with new Sandbox version 3.7.1

**Comment by tnein** [comment]
The bank-dev environment (https://openshift.adorsys.de/console/project/open-banking-gateway-bank-dev) was updated to the newest sandbox version.

This includes the following versions:

- ledgers @ 3.4
- xs2a-connector @ 7.4.1
- xs2a-services (consent-management-system, aspsp-profile) @ 7.4
- sandbox-services (certificate-generator, developer-portal-ui, online-banking, online-banking-ui, tpp-rest-server, tpp-ui) @ 3.7.1

As you can read here:
https://github.com/adorsys/XS2A-Sandbox/blob/master/docs/release_notes/Release_notes_3.7.md
the sandbox team added a new service - Tpp Administration GUI.
This is not yet included in the update. We should decide if we need it or not.
