### ISSUE TITLE
Fix smoke test case 'testTransactionListWithConsentUsingRedirectAllAccountsConsent'

### ISSUE THREAD

**Issue by vladimir-nechai** [adorsys/open-banking-gateway#745]
Currently smoke test 'testTransactionListWithConsentUsingRedirectAllAccountsConsent' fails the assertion to contain only these values:
  <[-150.00, -100.00, -2300.00, -250.00, 2300.00, -900.00, -700.00, 30000.00]>

**Comment by VanessaAhmad** [comment]
generate new user for each running test using Sandbox API
or create new user manually if not possible
