### ISSUE TITLE
No register in consent ui for pis

### ISSUE THREAD

**Issue by electronicpeter** [adorsys/open-banking-gateway#766]
When user has to register in consent ui, this is not possible in case of pis. For ais it is working fine. Currrently consent-ui gets exception:
Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'pis/67910d53-c546-4084-af0c-5c5decb9727e/register' noMatchError@http://localhost:4200/vendor.js:106216:16 apply/<@http://localhost:4200/vendor.js:106180:28 error@http://localhost:4200/vendor.js:117749:31 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 notifyError@http://localhost:4200/vendor.js:114556:26 _error@http://localhost:4200/vendor.js:114281:21 error@http://localhost:4200/vendor.js:114989:18 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 _error@http://localhost:4200/vendor.js:115009:26 error@http://localhost:4200/vendor.js:114989:18 error@http://localhost:4200/vendor.js:117752:23 _complete@http://localhost:4200/vendor.js:122122:30 complete@http://localhost:4200/vendor.js:114995:18 _complete@http://localhost:4200/vendor.js:115013:26 complete@http://localhost:4200/vendor.js:114995:18 _complete@http://localhost:4200/vendor.js:115013:26 complete@http://localhost:4200/vendor.js:114995:18 _complete@http://localhost:4200/vendor.js:119718:30 complete@http://localhost:4200/vendor.js:114995:18 _complete@http://localhost:4200/vendor.js:115013:26 complete@http://localhost:4200/vendor.js:114995:18 subscribeToArray/<@http://localhost:4200/vendor.js:124404:16 _trySubscribe@http://localhost:4200/vendor.js:114439:25 subscribe@http://localhost:4200/vendor.js:114425:22 call@http://localhost:4200/vendor.js:119465:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:119672:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:118977:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:121598:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:122100:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:117736:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:119465:23 subscribe@http://localhost:4200/vendor.js:114420:31 subscribeToResult@http://localhost:4200/vendor.js:124520:23 _innerSub@http://localhost:4200/vendor.js:119710:116 _tryNext@http://localhost:4200/vendor.js:119704:14 _next@http://localhost:4200/vendor.js:119687:18 next@http://localhost:4200/vendor.js:114983:18 subscribeToArray/<@http://localhost:4200/vendor.js:124402:20 _trySubscribe@http://localhost:4200/vendor.js:114439:25 subscribe@http://localhost:4200/vendor.js:114425:22 call@http://localhost:4200/vendor.js:119672:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:121657:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:122100:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:119465:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:119465:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:119465:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:117736:23 subscribe@http://localhost:4200/vendor.js:114420:31 call@http://localhost:4200/vendor.js:119465:23 subscribe@http://localhost:4200/vendor.js:114420:31 subscribeToResult@http://localhost:4200/vendor.js:124520:23 _innerSub@http://localhost:4200/vendor.js:121514:115 _next@http://localhost:4200/vendor.js:121504:14 next@http://localhost:4200/vendor.js:114983:18 notifyNext@http://localhost:4200/vendor.js:121538:26 _next@http://localhost:4200/vendor.js:114278:21 next@http://localhost:4200/vendor.js:114983:18 subscribeToPromise/</<@http://localhost:4200/vendor.js:124488:24 invoke@http://localhost:4200/polyfills.js:3709:26 onInvoke@http://localhost:4200/vendor.js:90836:33 invoke@http://localhost:4200/polyfills.js:3708:52 run@http://localhost:4200/polyfills.js:3474:43 scheduleResolveOrReject/<@http://localhost:4200/polyfills.js:4205:36 invokeTask@http://localhost:4200/polyfills.js:3741:31 onInvokeTask@http://localhost:4200/vendor.js:90817:33 invokeTask@http://localhost:4200/polyfills.js:3740:60 runTask@http://localhost:4200/polyfills.js:3518:47 drainMicroTaskQueue@http://localhost:4200/polyfills.js:3909:35 invokeTask@http://localhost:4200/polyfills.js:3819:21 invokeTask@http://localhost:4200/polyfills.js:4953:14 globalZoneAwareCallback@http://localhost:4200/polyfills.js:4979:27

**Comment by VanessaAhmad** [comment]
Collins or Vladi should take this task
