### ISSUE TITLE
cancel button proper fix

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#887]
there has been a quick fix #802

**Comment by electronicpeter** [comment]
When FinTech UI receives 202 on LoT, clicking Cancel button on redirection screen does not prevent UI from sending the same request again. Basically, you cancel redirection, but UI sends the request again and gets 202, shows you redirection screen again, forming infinite loop.

Issue still valid today.

1. got consent for loa 
2. switched setting "retrieve new consent for lot"
3. clicked again on accounts
4. choosed account by clicking on it
5. press cancel in redirection window

**Comment by electronicpeter** [comment]
Hi, Valentyn, Hi Collins,
(hi Denys)

In my opinion, the redirect approach in FintechServer is wrong. Currently it is implemented like that: (done from Valentyn in the beginning as a quick fix)

FinTechUI:
- defines (ok,nok url) which are real endpoints in UI
- sends (ok,nok url) to FinTechServer

FintechServer:
- stores (ok,nok url) and uses new (ok2,nok2 url) as they are defined in
  application.yml. These endpoints are real endpoints in FintechUI too
- sends (ok2,nok2 url) to TPP
 
ConsentUI:
- after whole call is done/or aborted consentUI eventually redirects to (ok2,nok2 url)
   as given from FintechServer
   
FintechUI:
- UI of (ok2,nok2 url) show confirmation and do call to FintechServer

FintechServer:
- with help of redirectCode original (ok,nok url) are retrieved from database
- confirmation of call from fintechUI now contains original (ok,nok url)

FintechUI:
- eventually redirects to (ok,nok url)

I disliked this approach right from the beginning, as it involves FintechServer to have
knowledge of FintechUI endpoints (ok2, nok2 url).

What Valentyn and me in the beginning had as a common consensus is that FintechServer has
knowledge of FintechUI PREFIX (e.g. https://obg-fintechui/). But Postfix (like
/redirect-ok/ or /banks/account/) should be knowledge of UI and only UI.

To me, and obviously to Vladi UI code is not easy to understand.

So I would like to change code now like that:

-----------------------------------------------------------------

FinTechUI:
- defines (ok,nok url) which are real endpoints in UI
- sends (ok,nok url) to FinTechServer

FintechServer:
- adds FINTECH_SERVER PREFIX to (ok,nok url)
- sends FINTECH_SERVER PREFIX(ok,nok url) to TPP
 
ConsentUI:
- after whole call is done consentUI eventually redirects to
   FINTECH_SERVER PREFIX(ok,nok url) as given from FintechUI
   
FintechUI:
- UI of (ok,nok) url show confirmation and do call to FintechServer

FintechServer:
- confirmation of call from fintechUI DOES NOT return any redirect URL

FintechUI:
- knows from previously stored information what to do next. Eg. show accounts,
   showTransactions, or showPayment.
 

To my opinion this makes code clearer and easier to understand. I would start with doing this tomorrow. If you have any objections, please let me know.

Peter

**Comment by electronicpeter** [comment]
fix in server:
If new consent should be retrieved, old will NOT be deleted. It just will be ignored. So it can happen, that more than one consent becomes valid. For that they are ordered by date.
fix in client:
If new consent should be retrieved, this is only done ONE TIME. Next time existing consent is used. Otherwise it would be endless loop.
