### ISSUE TITLE
Decide on whether to use runtime or compile time dependency injection

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/open-banking-gateway#9]
We will have to decide on wether to use 
- runtime dependency injection like spring boot or 
- compile time dependency injection like play, dagger-2, Micro?

Talking to valentine right now, we might also consider start with runtime DI, and move to compile time DI after the first MVP.

**Comment by valb3r** [comment]
@francis-pouatcha:
 Micro?
https://micronaut.io/
