### ISSUE TITLE
Setup secrets for the Github actions

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#953]
We need the following secrets to be set for Github actions:

Maven-deploy secrets:
✅ GPG_PASSPHRASE
✅ GPG_SECRET_KEY
✅ GPG_OWNERTRUST
✅ SONATYPE_USERNAME
✅ SONATYPE_PASSWORD

Openshift secrets:
✅ OPENSHIFT_TOKEN

DockerHub secrets:
✅ DOCKERHUB_USER
✅ DOCKERHUB_PASS

**Comment by tnein** [comment]
@valb3r 
The variable name changed for the DockerHub credentials:
DOCKERHUB_USERNAME
DOCKERHUB_PASSWORD

**Comment by tnein** [comment]
https://github.com/adorsys/open-banking-gateway/pull/1030
